# Foreign Earned Income Exclusion Calculations

According to TurboTax,
>If you started or ended a job in a foreign country at any point during 2015, you will need to allocate, or clearly designate, what you earned abroad and what was earned at home...

>**How to allocate your income**

>First, determine the number of days you worked during 2015 before the foreign job started or after it ended. Divide that number by the total days you worked during the entire year. Then, multiply the result by your 2015 income. The result is the amount you earned before or after the foreign job. You must deduct this amount from your earned income before you figure out how much of your income can be applied to the foreign earned income exclusion. We'll help you with this in TurboTax.

**Total Days Worked in 2015**

It's generally understood that a year consists of 365 days, and the year 2015 was no exception.

The US government observed ten [federal holidays in 2015](https://www.opm.gov/policy-data-oversight/snow-dismissal-procedures/federal-holidays/#url=2015). In truth, I only observed New Year's and Christmas this year (yes, I'm lame). I also neglect the federal holidays observed along the Franco-Swiss border because I was working to some degree on all of those dates (fine, I'm very lame).

It's virtually certain that graduate students in high-energy physics are working on Saturdays, so those are considered work days in the following calculations. However, Sundays will not be considered as work days because I'm supposed to keep the sabbath.

In [3]:
import datetime

def daterange(start_date=None, end_date=None, include_end_date=True):
    """
    Inspired by this stackoverflow discussion:
    http://stackoverflow.com/questions/1060279.
    
    Parameters
    ----------
    start_date : datetime.date
        The start date of the date range.
    end_date : datetime.date
        The end date of the date range.
    include_end_date : bool
        Whether or not the end date is included in the rate.
        The default is True.
        
    Returns
    -------
    generator
        A generator function which yields consecutive
        dates between the given date boundaries.
    """
    number_of_days = (end_date - start_date).days
    
    # The days attribute of a timedelta object returned by the
    # difference of date objects excludes the end date. To include
    # the end date, increment the number of days.
    if include_end_date:
        number_of_days += 1
        
    for n in range(number_of_days):
        yield start_date + datetime.timedelta(n)

# The start and end dates of 2015.
start_date = datetime.date(year=2015, month=1, day=1)
end_date = datetime.date(year=2015, month=12, day=31)

# How many days were in 2015? (Hint: This should equal 365.)
n_days = sum(1 for date in daterange(start_date, end_date))
print('Total Number of Days in 2015:', n_days)

# How many Sundays were in 2015?
# According to documentation for date.weekday():
# Return the day of the week as an integer, where Monday is 0 and Sunday is 6.
n_sundays = sum(1 for date in daterange(start_date, end_date) if date.weekday() == 6)
print('Total Number of Sundays in 2015:', n_sundays)

# How many working days were in 2015?
# Remember, I'm disregarding Sundays and the two holidays
# that I observed out of the ten US federal holidays.
n_workdays = n_days - n_sundays - 2
print('Total Number of Working Days in 2015:', n_workdays)

# How many days did I work in the United States
# prior to relocating and starting my foreign job?
relocation_date = datetime.date(year=2015, month=6, day=20)
n_workdays_US = sum(1 for date in daterange(start_date, end_date) if date < relocation_date)
print('Total Number of Working Days in 2015 (Before Foreign Job):', n_workdays_US)

Total Number of Days in 2015: 365
Total Number of Sundays in 2015: 52
Total Number of Working Days in 2015: 311
Total Number of Working Days in 2015 (Before Foreign Job): 170


Apparently, I've worked a total of **311** days in 2015. Since I relocated to CERN on June 19, 2015, **170** of those total working days were spent in the United States.

Suppose that my graduate research assistant salary is $22,000 for the following calculation.

In [5]:
salary = 22000
n_workdays_US = 170.
n_workdays = 311.

earnings_US = (n_workdays_US / n_workdays) * salary
print('Earnings (Before Foreign Job):', earnings_US)

Earnings (Before Foreign Job): 12025.72347266881


So $12,025 must be deducted from my total income in 2015. What remains is what the Foreign Earned Income (FEI) credit can potentially exempt.